name: Chatbot API
on:
  push:
    branches: ["main"]
  pull_request: 
    branches: ["main"]
env:
  API_KEY: ${{secrets.API_KEY}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: using the api key
        run: echo $API_KEY
