name: Chatbot API
on:
  push:
    branches: ["main"]
  pull_request: 
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: get secret api key as environment variable
        env:
          API_KEY: ${{secrets.API_KEY}}
